### ISSUE TITLE
Encoding optionals and NSDate

### ISSUE THREAD

**Issue by tosbaha** [Weebly/Cereal#1]
I have following struct

``` swift
struct ItemDetail {
    var message:String?
    var date:NSDate?
    var location:String?
    var status:ItemStatus //enum

    init(message:String?, date:NSDate?, location:String?, status:ItemStatus) {
        self.message = message
        self.date = date
        self.location = location
        self.status = status
    }
}
```

However Cereal doesn't allow me to encode optionals. I don't want to check for nil or use default values. How can I use Cereal to encode/decode above struct? Thanks.

**Comment by ketzusaka** [comment]
Hey @tosbaha,

Thanks for the feedback. I think using optionals is a great way to encode, and i'll make an update to the project soon to handle that. NSDate is also something that will be implicitly supported by Cereal soon; I just needed some point to push it up.

In the meantime, here's some code that should help you out! I didn't have context on what ItemStatus is, so I just made an enum with a couple values.

``` swift
import Foundation
import Cereal

struct ItemDetail: CerealType {
    var message:String?
    var date:NSDate?
    var location:String?
    var status:ItemStatus //enum

    init(message:String?, date:NSDate?, location:String?, status:ItemStatus) {
        self.message = message
        self.date = date
        self.location = location
        self.status = status
    }

    init(decoder: CerealDecoder) throws {
        message = try decoder.decode("message")
        date = try decoder.decode("date")
        location = try decoder.decode("location")
        status = try decoder.decode("status") ?? .Declined
    }

    func encodeWithCereal(inout encoder: CerealEncoder) throws {
        try encoder.encode(message, forKey: "message")
        try encoder.encode(date, forKey: "date")
        try encoder.encode(location, forKey: "location")
        try encoder.encode(status, forKey: "status")
    }
}

enum ItemStatus: CerealType {
    case Approved
    case Declined

    init(decoder: CerealDecoder) throws {
        guard let encoded: Int = try decoder.decode("status") else {
            self = .Approved
            return
        }

        if encoded == 2 {
            self = .Declined
        } else {
            self = .Approved
        }
    }

    func encodeWithCereal(inout encoder: CerealEncoder) throws {
        let encoded = self == .Declined ? 2 : 1
        try encoder.encode(encoded, forKey: "status")
    }
}

extension CerealEncoder {
    func encode(item: CerealRepresentable?, forKey key: String) throws {
        guard let unwrapped = item else { return }
        try encode(unwrapped, forKey: key)
    }

    func encode(date: NSDate?, forKey key: String) throws {
        guard let unwrapped = date else { return }
        try encode(unwrapped.timeIntervalSince1970, forKey: key)
    }
}

extension CerealDecoder {
    func decode(key: String) throws -> NSDate? {
        guard let data: Double = try decode(key) else {
            return nil
        }

        return NSDate(timeIntervalSince1970: data)
    }
}
```

**Comment by tosbaha** [comment]
Thanks for the code. Since I am trying to share some information between iOS App and WatchOS extension, optionals and NSDate is very important for me. Because I only want to share part of the class with WatchOS, I wonder if following is possible. Let's say I have a class

``` swift
class Item:CerealType {
    var name:String?
    var count = 1
    var id:String
    var startDate:NSDate?
    var updateDate:NSDate?
    var detail:Array<ItemDetail> = []
    var sender:String?

}
```

I want to share just part of it.Let's say only encode/decode `name, id,startDate, detail`. If I omit others in encoder/decoder functions will it work? I tried other serialization libraries they all required to me to initialize optionals even if they are not required. Only way I come up is, to create some proxy class and get the properties I want from `Item` class to proxy class. I hope you continue to develop this library. It has a potential. I will try to use your library later on and give feedback when you add mentioned features. Thanks again.

**Comment by ketzusaka** [comment]
Yup, you can definitely only encode and decode what you want :) I'll keep this issue updated as I add those requested features in.

**Comment by ketzusaka** [comment]
I've pushed a new version, 1.0.1, that incorporates optionals in encoders. I'll begin work on adding NSDate in there tomorrow, and it should be in by the middle of the week :)

**Comment by ketzusaka** [comment]
I've pushed a new version, 1.1.0, that includes NSDate as part of the built-in encodable/decodable types. Thanks again for the feedback!

**Comment by tosbaha** [comment]
Thanks for the update. I have following problem and I just can't find the reason of it.  I have following targets.
- iOS App
- Today's Extension
- Watch Extension

Some files have 2-3 targets like enums and some classes. For example, I don't want to use Cereal in Today's extension. Therefore I want to add some *extesion.swift file and add Cereal Functions there.
The thing is, if CerealType extension doesn't stay in the same file, I get following error
`Cannot invoke 'Gender.init' with an argument list of type '(rawValue: Int)'`
If I put extension and enum all together in same file, error goes away.

So;

Gender.swift

``` swift
enum Gender: Int {
    case Female
    case Male
}
```

GenderExtension.swift

``` swift
extension Gender: CerealType {
    private struct Keys {
        static let root = "gender"
    }

    init(decoder: CerealDecoder) throws {
        self.init(rawValue: try decoder.decode(Keys.root) ?? Gender.Female.rawValue)!
    }

    func encodeWithCereal(inout cereal: CerealEncoder) throws {
        try cereal.encode(rawValue, forKey: Keys.root)
    }
}
```

**Comment by ketzusaka** [comment]
Are you using a cocoa pod for Cereal or just copying the files into your project?

**Comment by tosbaha** [comment]
I am copying the files. Also following workaround fixes the problem
add following to Gender.swift

``` swift
    init?(raw: Int) {
        self.init(rawValue: raw)
    }
```

then in GenderExtension.swift

``` swift
    init(decoder: CerealDecoder) throws {
        self.init(raw: try decoder.decode(Keys.root) ?? Gender.Female.rawValue)!
    }
```

It seems, Enum Extensions can't get init from other files. This SO post has the same question. http://stackoverflow.com/questions/27390989/swift-enum-with-custom-initializer-loses-rawvalue-initializer

**Comment by tosbaha** [comment]
I have encountered another problem. If I add CerealType by extension to class again with seperate file, I get following error.
`Initializer requirement 'init(decoder:)' can only be satisfied by a `required` initializer in the definition of non-final class 'Item'` If I make it convenince initializer then I get 
`Initializer requirement 'init(decoder:)' can only be satisfied by a `required` initializer in the definition of non-final class 'Item'` It seems it is very hard to add CerealType conformance to existing class without adding initializers to same file. I hope you can find a workaround for this. I think only way is to use adding a function like `decodeWithCereal` instead of init.

**Comment by ketzusaka** [comment]
I've you tried marking the unit method as required in your extension?

**Comment by tosbaha** [comment]
I attached two version. First commented one compiles. Second one, doesn't compile and gives above errors that I mentioned. 

``` swift
enum ItemStatus: Int,CerealType {
    case Approved
    case Declined
    private struct Keys {
        static let status = "status"
    }

    init(decoder: CerealDecoder) throws {
        self.init(rawValue: try decoder.decode(Keys.status) ?? ItemStatus.Approved.rawValue)!
    }

    func encodeWithCereal(inout cereal: CerealEncoder) throws {
        try cereal.encode(rawValue, forKey: Keys.status)
    }
}

enum ItemType: Int,CerealType {
    case Book
    case Computer
    private struct Keys {
        static let type = "type"
    }

    init(decoder: CerealDecoder) throws {
        self.init(rawValue: try decoder.decode(Keys.type) ?? ItemType.Book.rawValue)!
    }

    func encodeWithCereal(inout cereal: CerealEncoder) throws {
        try cereal.encode(rawValue, forKey: Keys.type)
    }
}

struct ItemDetail {
    var message:String?
    var date:NSDate?
    var location:String?
    var status:ItemStatus //enum

    init(message:String?, date:NSDate?, location:String?, status:ItemStatus) {
        self.message = message
        self.date = date
        self.location = location
        self.status = status
    }
}

//WORKING Version
//class Item:CerealType {
//    var name:String?
//    var count = 1
//    var id:String
//    var type:ItemType
//    var startDate:NSDate?
//    var updateDate:NSDate?
//    var detail:Array<ItemDetail> = []
//    var sender:String?
//    
//    init(id:String,type:ItemType) {
//        self.id = id
//        self.type = type
//    }
//    private struct Keys {
//        static let id = "id"
//        static let type = "type"
//        static let startDate = "startDate"
//    }
//    
//     required convenience init(decoder: CerealDecoder) throws {
//        
//        let id:String = try decoder.decode(Keys.id)!
//        let type:ItemType = try decoder.decode(Keys.type)!
//        let startDate:NSDate? = try decoder.decode(Keys.startDate)
//        self.init(id:id,type:type)
//        self.startDate = startDate
//    }
//    
//    func encodeWithCereal(inout cereal: CerealEncoder) throws {
//        try cereal.encode(id, forKey: Keys.id)
//        try cereal.encode(type, forKey: Keys.type)
//        try cereal.encode(startDate, forKey: Keys.startDate)
//
//    }
//    
//}

//NON WORKING Version

class Item {
    var name:String?
    var count = 1
    var id:String
    var type:ItemType
    var startDate:NSDate?
    var updateDate:NSDate?
    var detail:Array<ItemDetail> = []
    var sender:String?

    init(id:String,type:ItemType) {
        self.id = id
        self.type = type
    }

}

extension Item: CerealType {

    private struct Keys {
        static let id = "id"
        static let type = "type"
        static let startDate = "startDate"
    }

     required init(decoder: CerealDecoder) throws {

        let id:String = try decoder.decode(Keys.id)!
        let type:ItemType = try decoder.decode(Keys.type)!
        let startDate:NSDate? = try decoder.decode(Keys.startDate)
        self.init(id:id,type:type)
        self.startDate = startDate
    }

    func encodeWithCereal(inout cereal: CerealEncoder) throws {
        try cereal.encode(id, forKey: Keys.id)
        try cereal.encode(type, forKey: Keys.type)
        try cereal.encode(startDate, forKey: Keys.startDate)

    }
}


```

EDIT: If I mark class as final, it compiles too.

``` swift
final class Item {
    var name:String?
    var count = 1
    var id:String
    var type:ItemType
    var startDate:NSDate?
    var updateDate:NSDate?
    var detail:Array<ItemDetail> = []
    var sender:String?

    init(id:String,type:ItemType) {
        self.id = id
        self.type = type
    }

}

extension Item: CerealType {

    private struct Keys {
        static let id = "id"
        static let type = "type"
        static let startDate = "startDate"
    }

       convenience init(decoder: CerealDecoder) throws {
        let id:String = try decoder.decode(Keys.id)!
        let type:ItemType = try decoder.decode(Keys.type)!
        let startDate:NSDate? = try decoder.decode(Keys.startDate)
        self.init(id:id,type:type)
        self.startDate = startDate

    }

    func encodeWithCereal(inout cereal: CerealEncoder) throws {
        try cereal.encode(id, forKey: Keys.id)
        try cereal.encode(type, forKey: Keys.type)
        try cereal.encode(startDate, forKey: Keys.startDate)

    }
}
```

**Comment by ketzusaka** [comment]
Interesting about `final`. I believe the issue here is just with the swift compiler itself. If you add required initializers in extensions, it can become ambiguous which designated initializer's can be used. By marking it final, the compiler knows that it won't have that ambiguity in other compilation units. I feel like this is a problem they will be able to solve in the future though.

I don't think adding a static/class method would work here; Cereal still needs to know how to initialize your types, so it must have an initializer requirement regardless. And due to how Swift handles initializers you'd probably have to make everything optional if you couldn't set the variables in a real initializer.
