### ISSUE TITLE
Query: Does Cereal work with Linux Swift?

### ISSUE THREAD

**Issue by lloydsargent** [Weebly/Cereal#12]
I’m currently working with Swift 3.0. Eventual goal is port apps from Linux to OS X.

**Comment by ketzusaka** [comment]
It mostly does. Unfortunately theres an inconsistency in NSURL between the OS X version and the version built with Linux. The `value.absoluteString` at CerealEncoder.swift:325 needs to be written as `value.absoluteString!` on Linux right now. I'm going to file a PR against the foundation library to fix this inconsistency, but until then, you can alter that.

I'll also update Cereal's repo to be friendly with SPM soon.

**Comment by lloydsargent** [comment]
Awesome!

**Comment by ketzusaka** [comment]
Quick update on this!

My [PR to fix the inconsistency](https://github.com/apple/swift-corelibs-foundation/commit/0f4a0dfa23c6c5b8f3f72c07ee5cff4c7fabc27b) was merged & is now part of the latest snapshot. I'll be working on getting the code to compile under both Swift 3 and Swift 2.2 over the next week or so, and once that's done we'll be fully linux compatible for the development snapshots =)
